import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import "./WhyUsPage.css";
import { gsap_transformation } from "../js/gsap.js";
import { useGSAP } from "@gsap/react";
import experience from "../assets/whyus-experience.jpg";
import personlized from "../assets/whyus-personlized.jpg";
import listing from "../assets/whyus-listing.jpg";
import transparency from "../assets/whyus-transparency.jpg";
function WhyUsPage() {
    useGSAP(() => {
        gsap_transformation();
    }, []);
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "page-container", children: [_jsx("div", { className: "left-container", children: _jsxs("div", { className: "left-content", children: [_jsx("h1", { children: "Why Us" }), _jsxs("div", { className: "left-text", children: [_jsxs("section", { className: "left-description", children: [_jsx("h2", { children: "Expertise in Real Estate" }), _jsxs("ul", { children: [_jsx("li", { children: "Our team consists of seasoned professionals with extensive knowledge of the local market. We provide insights and guidance to help you make informed property decisions." }), _jsx("li", { children: "With years of experience, we understand the nuances of buying, selling, and renting properties, ensuring a seamless experience for our clients." })] })] }), _jsxs("section", { className: "left-description", children: [_jsx("h2", { children: "Personalized Service" }), _jsxs("ul", { children: [_jsx("li", { children: "We believe in a tailored approach. Our agents take the time to understand your unique needs and preferences, providing solutions that fit your lifestyle and budget." }), _jsx("li", { children: "From initial consultation to closing, we are committed to being by your side every step of the way, ensuring you feel supported and informed." })] })] }), _jsxs("section", { className: "left-description", children: [_jsx("h2", { children: "Comprehensive Listings" }), _jsxs("ul", { children: [_jsx("li", { children: "Our extensive database features a wide range of properties, from cozy apartments to luxurious estates. Whatever your requirements, we have options that will meet your expectations." }), _jsx("li", { children: "We regularly update our listings to ensure that you have access to the latest properties on the market, giving you a competitive edge." })] })] }), _jsxs("section", { className: "left-description", children: [_jsx("h2", { children: "Transparent Process" }), _jsxs("ul", { children: [_jsx("li", { children: "We prioritize transparency and integrity in all our dealings. You will receive clear communication throughout the buying or selling process, with no hidden fees or surprises." }), _jsx("li", { children: "Our commitment to ethical practices means you can trust us to represent your best interests, fostering long-term relationships built on trust." })] })] })] })] }) }), _jsx("div", { className: "right-container", children: _jsx("div", { className: "right-content", children: _jsxs("div", { className: "right-card", children: [_jsx("img", { className: "desktopPhoto", src: experience, alt: "desktopPhoto-experience" }), _jsx("img", { className: "desktopPhoto", src: personlized, alt: "desktopPhoto-personlized" }), _jsx("img", { className: "desktopPhoto", src: listing, alt: "desktopPhoto-listing" }), _jsx("img", { className: "desktopPhoto", src: transparency, alt: "desktopPhoto-transparency" })] }) }) })] }) }));
}
export default WhyUsPage;
