import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import rightmoveLogo from "./assets/rightmove-logo.png";
import onthemarketLogo from "./assets/onTheMarket-logo.png";
import zooplaLogo from "./assets/zoopla-logo.png";
import "./AboutUs.css";
function AboutUs() {
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "container fade-in-container", id: "about-us-container", children: [_jsx("h1", { children: "About Us" }), _jsxs("div", { className: "container", id: "about-us-content-container", children: [_jsxs("div", { className: "container", id: "about-us-text-container", children: [_jsx("p", { children: "Since 2010, AltyProperty has established itself as one of the leading Estate Agents in the area, specializing in Residential Sales and Property Rentals and Management." }), _jsx("p", { children: "Operating from offices in Altrincham and Sale, with a dedicated Property Rentals office in Altrincham covering all areas, we sell and let properties across:" }), _jsxs("ul", { children: [_jsx("li", { children: "Altrincham" }), _jsx("li", { children: "Hale" }), _jsx("li", { children: "Hale Barns" }), _jsx("li", { children: "Bowdon" }), _jsx("li", { children: "Timperley" }), _jsx("li", { children: "Sale" }), _jsx("li", { children: "Brooklands" }), _jsx("li", { children: "Sale Moor" }), _jsx("li", { children: "Ashton on Mersey" })] }), _jsx("p", { children: "Our 30-strong, close-knit team of property and logistics experts really love to help people find their way to their new home!" }), _jsx("h2", { children: "The Directors" }), _jsxs("div", { className: "team-member", children: [_jsx("h3", { children: "James A. Alty MNAEA MARLA" }), _jsx("p", { children: "Principal, oversees the running of the business and is based at the Altrincham Office. He started his Estate Agency career in 1995 and has lived in the area all his life." })] }), _jsxs("div", { className: "team-member", children: [_jsx("h3", { children: "Sarah Jones MNAEA" }), _jsx("p", { children: "Director of the Sale Office, joined a local Estate Agency in 2000 before starting up AltyProperty alongside James. She lives in Timperley, having grown up in Sale." })] }), _jsxs("div", { className: "team-member", children: [_jsx("h3", { children: "Emily Smith FNAEA" }), _jsx("p", { children: "Director of the Altrincham Office and part of the AltyProperty team since 2008. Emily lives in Altrincham and has grown up in the area." })] }), _jsx("p", { children: "With directors of the business running the offices, you can be assured of a completely hands-on and personal service that can only be offered by an owner-run business." }), _jsxs("div", { className: "about-us-ahref-container", children: [_jsx("a", { href: "/", children: "Find Out More" }), _jsx("a", { href: "/about/reviews", children: "Our Reviews" })] })] }), _jsxs("div", { className: "container", id: "about-us-award-container", children: [_jsx("span", { children: " Find us on... " }), _jsx("img", { src: rightmoveLogo, alt: "rightmove-logo" }), _jsx("img", { src: onthemarketLogo, alt: "onthemarket-logo" }), _jsx("img", { src: zooplaLogo, alt: "zoopla-logo" })] })] })] }) }));
}
export default AboutUs;
