import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import "./ReviewCarousel.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import google5StarReview from "./assets/google-5star-review.webp";
function ReviewCarousel() {
    return (_jsx(_Fragment, { children: _jsxs("div", { id: "carouselExampleAutoplaying", className: "carousel slide fade-in-container", "data-bs-ride": "carousel", children: [_jsxs("div", { className: "carousel-inner", children: [_jsx("div", { className: "carousel-item active", "data-bs-interval": "5000", children: _jsx("div", { className: "carousel-review-card-background", children: _jsxs("div", { className: "carousel-review-card-content", children: [_jsx("img", { src: google5StarReview, alt: "" }), _jsx("h3", { children: "I recently used their service. It was a excellent experience. Thank you." }), _jsx("h5", { children: "Kate Arthus" })] }) }) }), _jsx("div", { className: "carousel-item", "data-bs-interval": "5000", children: _jsx("div", { className: "carousel-review-card-background", children: _jsxs("div", { className: "carousel-review-card-content", children: [_jsx("img", { src: google5StarReview, alt: "" }), _jsx("h3", { children: "I love how easy it was to compare different properties side by side. The neighborhood insights were particularly useful. Will definitely use this site again!" }), _jsx("h5", { children: "David W." })] }) }) }), _jsx("div", { className: "carousel-item", "data-bs-interval": "5000", children: _jsx("div", { className: "carousel-review-card-background", children: _jsxs("div", { className: "carousel-review-card-content", children: [_jsx("img", { src: google5StarReview, alt: "" }), _jsx("h3", { children: "Great selection of properties! The detailed descriptions and high-quality photos really helped me visualize my future home. A few more virtual tours would be a plus!" }), _jsx("h5", { children: "Sarah L." })] }) }) })] }), _jsxs("button", { className: "carousel-control-prev", type: "button", "data-bs-target": "#carouselExampleAutoplaying", "data-bs-slide": "prev", children: [_jsx("span", { className: "carousel-control-prev-icon", "aria-hidden": "true" }), _jsx("span", { className: "visually-hidden", children: "Previous" })] }), _jsxs("button", { className: "carousel-control-next", type: "button", "data-bs-target": "#carouselExampleAutoplaying", "data-bs-slide": "next", children: [_jsx("span", { className: "carousel-control-next-icon", "aria-hidden": "true" }), _jsx("span", { className: "visually-hidden", children: "Next" })] })] }) }));
}
export default ReviewCarousel;
